---
title: "locho_study"
output: html_notebook
---


```{r load packages}
Sys.time()

library(tidyverse)
```


```{r plot quality}
Sys.time()

qual <- read.delim("quality/fastx_F-50179071-003S_r1_stats.csv", header = TRUE)

ggplot(qual, aes(x = column, group = column)) +
  theme_bw() +
  geom_boxplot(stat = "identity", color="darkgrey", fill="lightgrey", alpha=0.2, 
    aes(lower = Q1, 
        upper = Q3,
        middle = mean,
        ymin = min,
        ymax = max)) 

ggplot(qual, aes(x = column, y = mean)) +
  theme_bw() +
  geom_line(color = "red") +
  scale_x_continuous(breaks = seq(0, 151, by = 10)) +
  scale_y_continuous(breaks = seq(0, 40, len = 5))


```

## filter blast data by coordinates
```{r filter blast}
Sys.time()

library(GenomicRanges)
library(plyranges)

blast_rslt <- read.table("annotations/blastx.outfmt6", header = FALSE, sep = "\t")

colnames(blast_rslt) <- c("query", "sseqid", "pident", "length", "mismatch", "gapopen", 
                          "qstart", "qend", "sstart", "send", "evalue", "bitscore")

test <- blast_rslt %>% dplyr::select(query, sseqid, sstart, send, evalue) 

test <- test %>% 
  mutate(i_start = case_when(sstart < send ~ sstart,
                             send < sstart ~ send))

test <- test %>% 
  mutate(i_end = case_when(sstart < send ~ send,
                           send < sstart ~ sstart))

test <- test %>% 
  mutate(strand = case_when(sstart < send ~ "+", 
                            send < sstart ~ "-"))

test <- test %>% 
  select(query, sseqid, i_start, i_end, evalue, strand)

colnames(test) <- c("query", "seqnames", "start", "end", "evalue", "strand")

test_irange <- test %>% 
  as_granges()

test_disjoin <- reduce(test_irange,with.revmap = TRUE)

list_revmap <- as.data.frame(mcols(test_disjoin))

filtered_data <- c()
for(i in 1:nrow(list_revmap)){
  filtered_data <- c(filtered_data, (slice(list_revmap, i) %>% 
                                       unlist(use.names=FALSE))[which.min(slice(test,  slice(list_revmap, i) %>%
                                                                                  unlist(use.names=FALSE))$evalue)])
}

best_hits <- slice(test, filtered_data)
```


TODO: HIGH PRIORITY cluster analysis
TODO: account for repeated measure with diet as main effect and order of diet as repeated measure
TODO: WGCNA 
TODO: RLQ - which transcription factors controlling expression of each gene [Baty et al., 2013](https://pmc.ncbi.nlm.nih.gov/articles/PMC3686578/); [RLQ R tutorial](https://rfrelat.github.io/RLQ.html)


### END ###